x-project-base: &project-base
  restart: always
  networks:
    - remixide

networks:
  remixide:

services:
  remixide:
    image: remixproject/remix-ide:latest
    container_name: remixide-latest
    ports: 
      - 8080:80
      - 65520:65520
